version: 2

references:
  default: &default
    docker:
      - image: circleci/python:3.8
    working_directory: ~/repo
  cache_key: &cache_key v1-dependencies-{{ checksum "requirements.txt" }}
  restore_cache_requirements: &restore_cache_requirements
    restore_cache:
      keys:
        - *cache_key
  save_cache_requirements: &save_cache_requirements
    save_cache:
      paths:
        - ./venv
      key: *cache_key

jobs:
  test:
    <<: *default
    steps:
      - checkout
      - *restore_cache_requirements
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - *save_cache_requirements
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python -m pytest tests/ -v
  build:
    <<: *default
    steps:
      - checkout
      - *restore_cache_requirements
      - run:
          name: run sam build
          command: |
            . venv/bin/activate
            sam build
  deploy:
    <<: *default
    steps:
      - checkout
      - *restore_cache_requirements
      - run:
          name: run sam deploy
          command: |
            . venv/bin/activate
            sam build
            python manage.py deploy

workflows:
  version: 2
  test_and_build_and_deploy:
    jobs:
      - test
      - build:
          requires:
            - test
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - integrate
